upstream {

  # 国内DNS
  alidns: 'udp://223.5.5.5:53'
  alidns_backup: 'udp://223.6.6.6:53'

  # 国外DNS
  googledns: 'tcp://8.8.8.8:53'
}


routing {

  request {

    # 广告优先
    qname(geosite:category-ads-all) -> reject


    # 国内域名
    qname(geosite:cn) -> alidns


    # 其他
    fallback: googledns
  }
}
